version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "8000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sapthashreek
      MONGO_INITDB_ROOT_PASSWORD: MjY4NTItc2FwdGhh
